#!/bin/bash

if ! lilvali; then
  echo "lilvali failed. Push aborted."
  exit 1
fi

if ! python demo/basic >/dev/null; then
  echo "Demo failed. Push aborted."
  exit 1
fi

# Run the test suite
if ! (bash tests/test.sh) then
  echo "Tests failed. Push aborted."
  exit 1
fi

